name: Lighthouse
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  lhci:
    if: ${{ !(github.event_name == pull_request && github.actor == dependabot[bot]) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci && npm run build
      - name: Run Lighthouse on deployed page
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://coderdeltalan.github.io/cdlan-portfolio/
          runs: 3
          uploadArtifacts: true
          temporaryPublicStorage: true
