name: Link Check
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  lychee:
    if: ${{ !(github.event_name == pull_request && github.actor == dependabot[bot]) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci && npm run build
      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --max-concurrency 8 dist/**/*.html
